SET SQL DIALECT 3;

/* CREATE DATABASE 'C:\Bingo\BingoControl.GDB' PAGE_SIZE 4096

 DEFAULT CHARACTER SET WIN1252 */

/*  External Function declarations */

DECLARE EXTERNAL FUNCTION RDB$GET_CONTEXT
VARCHAR(80) CHARACTER SET NONE, VARCHAR(80) CHARACTER SET NONE
RETURNS VARCHAR(255) CHARACTER SET NONE FREE_IT
ENTRY_POINT 'get_context' MODULE_NAME 'system_module';


DECLARE EXTERNAL FUNCTION RDB$SET_CONTEXT
VARCHAR(80) CHARACTER SET NONE, VARCHAR(80) CHARACTER SET NONE, VARCHAR(255) CHARACTER SET NONE
RETURNS INTEGER BY VALUE 
ENTRY_POINT 'set_context' MODULE_NAME 'system_module';


DECLARE EXTERNAL FUNCTION SUBSTR
CSTRING(80) CHARACTER SET WIN1252, SMALLINT, SMALLINT
RETURNS CSTRING(80) CHARACTER SET WIN1252 FREE_IT
ENTRY_POINT 'IB_UDF_substr' MODULE_NAME 'ib_udf';


/* Domain definitions */
CREATE DOMAIN "LOGICAL" AS CHAR(1) CHARACTER SET WIN1252
	 DEFAULT 'F'
	 CHECK (VALUE IN ('T','F')) NOT NULL;

/* Table: CARTELAS, Owner: SYSDBA */

CREATE TABLE "CARTELAS" 
(
  "CodSorteio"	 INTEGER NOT NULL,
  "NumeroCartela"	 INTEGER NOT NULL,
  "Texto"	 VARCHAR(100) CHARACTER SET WIN1252,
CONSTRAINT "PK_Cartelas" PRIMARY KEY ("CodSorteio", "NumeroCartela")
);

/* Table: LOCAL, Owner: SYSDBA */

CREATE TABLE "LOCAL" 
(
  "Codigo"	 INTEGER NOT NULL,
  "NomeLocal"	 VARCHAR(60) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  "Endereco"	 VARCHAR(100) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
CONSTRAINT "PK_Local" PRIMARY KEY ("Codigo")
);

/* Table: PREMIOS, Owner: SYSDBA */

CREATE TABLE "PREMIOS" 
(
  "CodSorteio"	 INTEGER NOT NULL,
  "NumeroPremio"	 INTEGER NOT NULL,
  "Descricao"	 VARCHAR(20) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
CONSTRAINT "PK_Premios" PRIMARY KEY ("CodSorteio", "NumeroPremio")
);

/* Table: SORTEIOS, Owner: SYSDBA */

CREATE TABLE "SORTEIOS" 
(
  "Codigo"	 INTEGER NOT NULL,
  "NumeroLoop"	 INTEGER NOT NULL,
  "NomeSorteio"	 VARCHAR(60) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  "CodLocal"	 INTEGER,
  "Data"	 DATE,
  "Hora"	 TIME,
  "PrecoCartela"	 DOUBLE PRECISION,
  "Apoio"	 VARCHAR(60) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  "DataCadastro"	 DATE,
CONSTRAINT "PK_Sorteios" PRIMARY KEY ("Codigo")
);

/* Table: USUARIOS, Owner: SYSDBA */

CREATE TABLE "USUARIOS" 
(
  "Codigo"	 INTEGER NOT NULL,
  "Nome"	 VARCHAR(20) CHARACTER SET WIN1252 NOT NULL,
  "Senha"	 VARCHAR(10) CHARACTER SET WIN1252 NOT NULL,
  "Perfil"	 VARCHAR(10) CHARACTER SET WIN1252,
  "Ativo"	 LOGICAL  DEFAULT 'F' NOT NULL,
CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Codigo")
);


/* Grant Roles for this database */


/* Grant permissions for this database */
